src/Flickr/Models/Picture.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Flickr.Models
{
    [Table("Pictures")]
    public class Picture
    {
        [Key]
        public int PictureId { get; set; }
        public string Url { get; set; }
        public string Caption { get; set; }
        public virtual FlickrUser User { get; set; }
    }
}

src/Flickr/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Flickr.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Flickr.Controllers 
{
    
    public class CommentsController : Controller
    {
        private FlickrDbContext _db = new FlickrDbContext();
        // GET: /<controller>/
        public IActionResult Create()
        {
            ViewBag.PictureId = new SelectList(_db.Pictures, "PictureId", "Caption");
            return View();
        }
        [HttpPost]
        public IActionResult Create(Comment comment)
        {
            _db.Comments.Add(comment);
            _db.SaveChanges();
            return RedirectToAction("Index", "Pictures");
        }

        public IActionResult Edit(int id)
        {
            ViewBag.PictureId = new SelectList(_db.Pictures, "PictureId", "Caption");
            var thisComment = _db.Comments.FirstOrDefault(comments => comments.CommentId == id);
            return View(thisComment);
        }

        [HttpPost]
        public IActionResult Edit(Comment comment)
        {
            _db.Entry(comment).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index", "Pictures");
        }

        public IActionResult Delete(int id)
        {
            var thisComment = _db.Comments.FirstOrDefault(comments => comments.CommentId == id);
            return View(thisComment);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var thisComment = _db.Comments.FirstOrDefault(comments => comments.CommentId == id);
            _db.Comments.Remove(thisComment);
            _db.SaveChanges();
            return RedirectToAction("Index","Pictures");
        }
    }
}

src/Flickr/Controllers/PicturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Flickr.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace Flickr.Controllers
{
    [Authorize]
    public class PicturesController : Controller
    {

        private readonly FlickrDbContext _db;
        private readonly UserManager<FlickrUser> _userManager;

        public PicturesController (UserManager<FlickrUser> userManager, FlickrDbContext db)
        {
            _userManager = userManager;
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            return View(_db.Pictures.Where(x => x.User.Id == currentUser.Id));
        }

        public IActionResult AllPictures()
        {

            return View(_db.Pictures.ToList());
        }

        public IActionResult Details(int id)
        {
            var thisPicture = _db.Pictures.Include(pictures => pictures.Comments).FirstOrDefault(pictures => pictures.PictureId == id);
            ViewBag.Tag = _db.Pictures
                .Include(picture => picture.PicturesTags)
                .ThenInclude(picturesTags => picturesTags.Tag)
                .Where(picture => picture.PictureId == id).ToList();

            return View(thisPicture);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Picture picture)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            picture.User = currentUser;
            _db.Pictures.Add(picture);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var thisPicture = _db.Pictures.FirstOrDefault(pictures => pictures.PictureId == id);
            return View(thisPicture);
        }

        [HttpPost]
        public IActionResult Edit(Picture picture)
        {
            _db.Entry(picture).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var thisPicture = _db.Pictures.FirstOrDefault(pictures => pictures.PictureId == id);
            return View(thisPicture);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var thisPicture = _db.Pictures.FirstOrDefault(pictures => pictures.PictureId == id);
            _db.Pictures.Remove(thisPicture);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/Flickr/Controllers/PicturesTagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Flickr.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;

namespace Flickr.Controllers
{
    public class PicturesTagsController : Controller
    {
        private FlickrDbContext db = new FlickrDbContext();
        private readonly UserManager<FlickrUser> _userManager;

        //public IActionResult Index()
        //{
        //    return View(db.ExperiencesPeoples.ToList());
        //}

        public PicturesTagsController(UserManager<FlickrUser> userManager, FlickrDbContext db)
        {
            _userManager = userManager;
        
        }

        public async Task<IActionResult> Create()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            ViewBag.PictureId = new SelectList(db.Pictures.Where(x => x.User.Id == currentUser.Id), "PictureId", "Caption");
            ViewBag.TagId = new SelectList(db.Tags, "TagId", "Word");
            return View();
        }

        [HttpPost]
        public IActionResult Create(PictureTag pictureTag)
        {
            db.PicturesTags.Add(pictureTag);
            db.SaveChanges();
            return RedirectToAction("Index", "Pictures");
        }
    }
}

src/Flickr/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Flickr.Models;


namespace Flickr.Controllers
{
    public class TagsController : Controller
    {
        private FlickrDbContext _db = new FlickrDbContext();
        public IActionResult Index()
        {
            ViewBag.Picture = _db.Tags
               .Include(tag => tag.PicturesTags)
               .ThenInclude(picturesTags => picturesTags.Picture);
               //.Where(tag => tag.TagId == id).ToList();
            return View(_db.Tags.ToList());
        }

        public IActionResult Create()
        {
            ViewBag.PictureId = new SelectList(_db.Pictures, "PictureId", "Caption");
            return View();
        }
        [HttpPost]
        public IActionResult Create(Tag tag)
        {
            _db.Tags.Add(tag);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id, int picId)
        {
            ViewBag.TagId = new SelectList(_db.Tags, "PictureId", "Caption");
            ViewBag.PicId = picId;
            var thisTag = _db.Tags.FirstOrDefault(tags => tags.TagId == id);
            return View(thisTag);
        }

        [HttpPost]
        public IActionResult Edit(Tag tag, int picId)
        {
            _db.Entry(tag).State = EntityState.Modified;
            _db.SaveChanges();
            var pictureId = picId;
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var thisTag = _db.Tags.FirstOrDefault(tags => tags.TagId == id);
            return View(thisTag);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var thisTag = _db.Tags.FirstOrDefault(tags => tags.TagId == id);
            _db.Tags.Remove(thisTag);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/Flickr/Views/Pictures/AllPictures.cshtml
@model IEnumerable<Flickr.Models.Picture>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using System.Security.Claims

<h2>Here are your pictures, @User.Identity.Name</h2>

@if (Model.Any())
{
    <div class="row">
        @foreach (var listPicture in Model)
        {
            <div class="col-sm-4">
                <img class="index-picture" src="@Html.DisplayFor(modelPicture => listPicture.Url)" />
                <br />
                <p>@Html.ActionLink((string)listPicture.Caption, "Details", new { id = listPicture.PictureId })</p>
            </div>
        }
    </div>
}
else
{
    <p>No pictures have been added yet!</p>
}

<hr />
@Html.ActionLink("Create new", "Create")

@Html.ActionLink("Add tag to picture", "Create", "PicturesTags")

src/Flickr/Views/Pictures/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Flickr.Models.Picture

<h2>Add a new picture</h2>
<hr />
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Url)
    @Html.EditorFor(model => model.Url)

    @Html.LabelFor(model => model.Caption)
    @Html.EditorFor(model => model.Caption)


    <input type="submit" value="Create" />
}

@Html.ActionLink("Back to List", "Index")

src/Flickr/Views/Pictures/Delete.cshtml
@model Flickr.Models.Picture

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Are you sure you want to delete this?</h2>
<hr />
@Html.DisplayNameFor(model => model.Caption): @Html.DisplayFor(model => model.Caption)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

src/Flickr/Views/Pictures/Details.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Flickr.Models.Picture

<img src="@Html.DisplayFor(model => model.Url)" />
<br />
<br />

 <h2>@Html.DisplayFor(model => model.Caption)</h2>

<h3>Tags:</h3>
@if (Model.PicturesTags.Count != 0)
{
 
    @foreach (var pictureTags in Model.PicturesTags)
    {
        <p>@pictureTags.Tag.Word</p>
        <p> @Html.ActionLink("Edit", "Edit", "Tags", new { id = pictureTags.TagId }, new { picId = pictureTags.PictureId })</p>
            <p>@Html.ActionLink("Delete", "Delete", "Tags", new { id = pictureTags.TagId })</p>
    }
}
else
{
    <p>You haven't added any tags to this picture yet.</p>
}



<h3>Comments:</h3>
<ol>
    @if (Model.Comments.Count != 0)
    {
        @foreach (var comment in Model.Comments)
        {
            <li>
                <h5>@comment.Description</h5>
                <p>@Html.ActionLink("Edit", "Edit", "Comments", new { id = comment.CommentId })</p>
                <p>@Html.ActionLink("Delete", "Delete", "Comments", new { id = comment.CommentId })</p>
            </li>

        }
    }
    else
    {
        <p>There are no comments on this picture yet!</p>

    }
</ol>

<p>@Html.ActionLink("Leave a new comment", "Create", "Comments")</p>
<p>@Html.ActionLink("Leave a new tag", "Create", "Tags")</p>

<p>@Html.ActionLink("Back to my list", "Index")</p>
<p>@Html.ActionLink("Back to the list of all pictures", "AllPictures")</p>

src/Flickr/Views/Pictures/Edit.cshtml
@model Flickr.Models.Picture

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Edit</h2>
<hr />
<h4>Edit this picture: @Html.DisplayFor(model => model.Caption)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.PictureId)

    @Html.LabelFor(model => model.Url)
    @Html.EditorFor(model => model.Url)

    @Html.LabelFor(model => model.Caption)
    @Html.EditorFor(model => model.Caption)

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

src/Flickr/Views/Pictures/Index.cshtml
@model IEnumerable<Flickr.Models.Picture>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using System.Security.Claims

<h2>Here are your pictures, @User.Identity.Name</h2>

@if (Model.Any())
{
    <div class="row">
        @foreach (var listPicture in Model)
        {
            <div class="col-sm-4">
                <img class="index-picture" src="@Html.DisplayFor(modelPicture => listPicture.Url)" />
                <br />
                <p>@Html.ActionLink((string)listPicture.Caption, "Details", new { id = listPicture.PictureId }) | @Html.ActionLink("Edit", "Edit", new { id = listPicture.PictureId }) | @Html.ActionLink("Delete", "Delete", new { id = listPicture.PictureId })</p>
            </div>
        }
    </div>
}
else
{
    <p>No pictures have been added yet!</p>
}

<hr />
@Html.ActionLink("Create new", "Create")

@Html.ActionLink("Add tag to picture", "Create", "PicturesTags")